name: HubSystem
version: '1.0'
main: net.letstim.hubSystem.HubSystem
api-version: '1.21'

commands:
  timezone:
    description: Zeigt die aktuelle Zeit und verwaltet die Zeitzone
    usage: /<command> [reload|<timezone>]
    aliases: [tz]
  hubdebug:
    description: Debug-Befehle für Events
    usage: /<command> event <start|stop|status> <eventName>

permissions:
  hubsystem.timezone.admin:
    description: Erlaubt Admin-Befehle für RealTime
    default: op
  hubsystem.debug.event:
    description: Erlaubt Debug-Befehle für Events
    default: op

