name: HubSystem
version: '1.0'
main: net.letstim.hubSystem.HubSystem
api-version: '1.21'

commands:
  timezone:
    description: Zeigt die aktuelle Zeit und verwaltet die Zeitzone
    usage: /<command> [reload|<timezone>]
    aliases: [tz]
  fireworkdebug:
    description: Startet das Silvester-Feuerwerk fuer 1 Minute zum Testen
    usage: /<command>
    aliases: [fwdebug, testfeuerwerk]

permissions:
  hubsystem.timezone.admin:
    description: Erlaubt Admin-Befehle für RealTime
    default: op
  hubsystem.firework.debug:
    description: Erlaubt das Starten des Test-Feuerwerks
    default: op

